---
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install WebAssembly tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld
          clang --version
          lld --version
          npm install -g browserify

      - name: Install dependencies
        run: |
          npm install
          npm run postinstall

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: demos  # 包含 main.html 的目录
          branch: gh-pages  # 部署到的分支
